# Generated by Django 5.2.6 on 2025-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='language',
            field=models.CharField(choices=[('swahili', 'Kiswahili'), ('english', 'English')], default='swahili', max_length=10),
        ),
    ]
